/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiSignal {
  'generatedAt' : bigint,
  'signal' : { 'buy' : null } |
    { 'hold' : null } |
    { 'sell' : null },
  'confidence' : number,
  'symbol' : string,
}
export interface MarketData {
  'timestamp' : bigint,
  'price' : number,
  'symbol' : string,
}
export interface TradePosition {
  'closeTime' : [] | [bigint],
  'entryTime' : bigint,
  'side' : { 'buy' : null } |
    { 'sell' : null },
  'profitLoss' : [] | [number],
  'closePrice' : [] | [number],
  'quantity' : number,
  'entryPrice' : number,
  'symbol' : string,
}
export interface UserProfile {
  'balance' : number,
  'displayName' : string,
  'tradeHistory' : Array<TradePosition>,
  'email' : string,
  'openPositions' : Array<TradePosition>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMarketData' : ActorMethod<[MarketData], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateAiSignal' : ActorMethod<
    [string, { 'buy' : null } | { 'hold' : null } | { 'sell' : null }, number],
    undefined
  >,
  'getAiSignal' : ActorMethod<[string], AiSignal>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [Principal],
    {
      'totalTrades' : bigint,
      'openEquity' : number,
      'balance' : number,
      'winRate' : number,
    }
  >,
  'getMarketData' : ActorMethod<[string], Array<MarketData>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];