/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MarketData = IDL.Record({
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AiSignal = IDL.Record({
  'generatedAt' : IDL.Int,
  'signal' : IDL.Variant({
    'buy' : IDL.Null,
    'hold' : IDL.Null,
    'sell' : IDL.Null,
  }),
  'confidence' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const TradePosition = IDL.Record({
  'closeTime' : IDL.Opt(IDL.Int),
  'entryTime' : IDL.Int,
  'side' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
  'profitLoss' : IDL.Opt(IDL.Float64),
  'closePrice' : IDL.Opt(IDL.Float64),
  'quantity' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'balance' : IDL.Float64,
  'displayName' : IDL.Text,
  'tradeHistory' : IDL.Vec(TradePosition),
  'email' : IDL.Text,
  'openPositions' : IDL.Vec(TradePosition),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMarketData' : IDL.Func([MarketData], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateAiSignal' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({ 'buy' : IDL.Null, 'hold' : IDL.Null, 'sell' : IDL.Null }),
        IDL.Float64,
      ],
      [],
      [],
    ),
  'getAiSignal' : IDL.Func([IDL.Text], [AiSignal], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'totalTrades' : IDL.Nat,
          'openEquity' : IDL.Float64,
          'balance' : IDL.Float64,
          'winRate' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getMarketData' : IDL.Func([IDL.Text], [IDL.Vec(MarketData)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MarketData = IDL.Record({
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AiSignal = IDL.Record({
    'generatedAt' : IDL.Int,
    'signal' : IDL.Variant({
      'buy' : IDL.Null,
      'hold' : IDL.Null,
      'sell' : IDL.Null,
    }),
    'confidence' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const TradePosition = IDL.Record({
    'closeTime' : IDL.Opt(IDL.Int),
    'entryTime' : IDL.Int,
    'side' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
    'profitLoss' : IDL.Opt(IDL.Float64),
    'closePrice' : IDL.Opt(IDL.Float64),
    'quantity' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'balance' : IDL.Float64,
    'displayName' : IDL.Text,
    'tradeHistory' : IDL.Vec(TradePosition),
    'email' : IDL.Text,
    'openPositions' : IDL.Vec(TradePosition),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMarketData' : IDL.Func([MarketData], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateAiSignal' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'buy' : IDL.Null,
            'hold' : IDL.Null,
            'sell' : IDL.Null,
          }),
          IDL.Float64,
        ],
        [],
        [],
      ),
    'getAiSignal' : IDL.Func([IDL.Text], [AiSignal], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'totalTrades' : IDL.Nat,
            'openEquity' : IDL.Float64,
            'balance' : IDL.Float64,
            'winRate' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getMarketData' : IDL.Func([IDL.Text], [IDL.Vec(MarketData)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };