/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TradePosition {
    closeTime?: bigint;
    entryTime: bigint;
    side: Variant_buy_sell;
    profitLoss?: number;
    closePrice?: number;
    quantity: number;
    entryPrice: number;
    symbol: string;
}
export interface AiSignal {
    generatedAt: bigint;
    signal: Variant_buy_hold_sell;
    confidence: number;
    symbol: string;
}
export interface AdminStats {
    totalTrades: bigint;
    premiumUsers: bigint;
    platformWinRate: number;
    freeUsers: bigint;
    mostTradedSymbol: string;
    totalUsers: bigint;
}
export interface UserProfile {
    balance: number;
    displayName: string;
    tradeHistory: Array<TradePosition>;
    email: string;
    openPositions: Array<TradePosition>;
}
export interface MarketData {
    timestamp: bigint;
    price: number;
    symbol: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_buy_hold_sell {
    buy = "buy",
    hold = "hold",
    sell = "sell"
}
export enum Variant_buy_sell {
    buy = "buy",
    sell = "sell"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMarketData(data: MarketData): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    generateAiSignal(symbol: string, signal: Variant_buy_hold_sell, confidence: number): Promise<void>;
    getAdminStats(): Promise<AdminStats>;
    getAiSignal(symbol: string): Promise<AiSignal>;
    getCallerUserProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(user: Principal): Promise<{
        totalTrades: bigint;
        openEquity: number;
        balance: number;
        winRate: number;
    }>;
    getMarketData(symbol: string): Promise<Array<MarketData>>;
    getUserProfile(user: Principal): Promise<UserProfile>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    verifyAdminPin(pin: string): Promise<boolean>;
}
import type { AiSignal as _AiSignal, TradePosition as _TradePosition, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMarketData(arg0: MarketData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMarketData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMarketData(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async generateAiSignal(arg0: string, arg1: Variant_buy_hold_sell, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAiSignal(arg0, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAiSignal(arg0, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAiSignal(arg0: string): Promise<AiSignal> {
        if (this.processError) {
            try {
                const result = await this.actor.getAiSignal(arg0);
                return from_candid_AiSignal_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAiSignal(arg0);
            return from_candid_AiSignal_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(arg0: Principal): Promise<{
        totalTrades: bigint;
        openEquity: number;
        balance: number;
        winRate: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats(arg0);
            return result;
        }
    }
    async getMarketData(arg0: string): Promise<Array<MarketData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketData(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyAdminPin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPin(arg0);
            return result;
        }
    }
}
function from_candid_AiSignal_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AiSignal): AiSignal {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TradePosition_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradePosition): TradePosition {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closeTime: [] | [bigint];
    entryTime: bigint;
    side: {
        buy: null;
    } | {
        sell: null;
    };
    profitLoss: [] | [number];
    closePrice: [] | [number];
    quantity: number;
    entryPrice: number;
    symbol: string;
}): {
    closeTime?: bigint;
    entryTime: bigint;
    side: Variant_buy_sell;
    profitLoss?: number;
    closePrice?: number;
    quantity: number;
    entryPrice: number;
    symbol: string;
} {
    return {
        closeTime: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.closeTime)),
        entryTime: value.entryTime,
        side: from_candid_variant_n13(_uploadFile, _downloadFile, value.side),
        profitLoss: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.profitLoss)),
        closePrice: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.closePrice)),
        quantity: value.quantity,
        entryPrice: value.entryPrice,
        symbol: value.symbol
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generatedAt: bigint;
    signal: {
        buy: null;
    } | {
        hold: null;
    } | {
        sell: null;
    };
    confidence: number;
    symbol: string;
}): {
    generatedAt: bigint;
    signal: Variant_buy_hold_sell;
    confidence: number;
    symbol: string;
} {
    return {
        generatedAt: value.generatedAt,
        signal: from_candid_variant_n6(_uploadFile, _downloadFile, value.signal),
        confidence: value.confidence,
        symbol: value.symbol
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: number;
    displayName: string;
    tradeHistory: Array<_TradePosition>;
    email: string;
    openPositions: Array<_TradePosition>;
}): {
    balance: number;
    displayName: string;
    tradeHistory: Array<TradePosition>;
    email: string;
    openPositions: Array<TradePosition>;
} {
    return {
        balance: value.balance,
        displayName: value.displayName,
        tradeHistory: from_candid_vec_n9(_uploadFile, _downloadFile, value.tradeHistory),
        email: value.email,
        openPositions: from_candid_vec_n9(_uploadFile, _downloadFile, value.openPositions)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): Variant_buy_sell {
    return "buy" in value ? Variant_buy_sell.buy : "sell" in value ? Variant_buy_sell.sell : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    hold: null;
} | {
    sell: null;
}): Variant_buy_hold_sell {
    return "buy" in value ? Variant_buy_hold_sell.buy : "hold" in value ? Variant_buy_hold_sell.hold : "sell" in value ? Variant_buy_hold_sell.sell : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradePosition>): Array<TradePosition> {
    return value.map((x)=>from_candid_TradePosition_n10(_uploadFile, _downloadFile, x));
}
function to_candid_TradePosition_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradePosition): _TradePosition {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: number;
    displayName: string;
    tradeHistory: Array<TradePosition>;
    email: string;
    openPositions: Array<TradePosition>;
}): {
    balance: number;
    displayName: string;
    tradeHistory: Array<_TradePosition>;
    email: string;
    openPositions: Array<_TradePosition>;
} {
    return {
        balance: value.balance,
        displayName: value.displayName,
        tradeHistory: to_candid_vec_n19(_uploadFile, _downloadFile, value.tradeHistory),
        email: value.email,
        openPositions: to_candid_vec_n19(_uploadFile, _downloadFile, value.openPositions)
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closeTime?: bigint;
    entryTime: bigint;
    side: Variant_buy_sell;
    profitLoss?: number;
    closePrice?: number;
    quantity: number;
    entryPrice: number;
    symbol: string;
}): {
    closeTime: [] | [bigint];
    entryTime: bigint;
    side: {
        buy: null;
    } | {
        sell: null;
    };
    profitLoss: [] | [number];
    closePrice: [] | [number];
    quantity: number;
    entryPrice: number;
    symbol: string;
} {
    return {
        closeTime: value.closeTime ? candid_some(value.closeTime) : candid_none(),
        entryTime: value.entryTime,
        side: to_candid_variant_n22(_uploadFile, _downloadFile, value.side),
        profitLoss: value.profitLoss ? candid_some(value.profitLoss) : candid_none(),
        closePrice: value.closePrice ? candid_some(value.closePrice) : candid_none(),
        quantity: value.quantity,
        entryPrice: value.entryPrice,
        symbol: value.symbol
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_buy_sell): {
    buy: null;
} | {
    sell: null;
} {
    return value == Variant_buy_sell.buy ? {
        buy: null
    } : value == Variant_buy_sell.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_buy_hold_sell): {
    buy: null;
} | {
    hold: null;
} | {
    sell: null;
} {
    return value == Variant_buy_hold_sell.buy ? {
        buy: null
    } : value == Variant_buy_hold_sell.hold ? {
        hold: null
    } : value == Variant_buy_hold_sell.sell ? {
        sell: null
    } : value;
}
function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TradePosition>): Array<_TradePosition> {
    return value.map((x)=>to_candid_TradePosition_n20(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
